# Generated by Django 6.0.5 on 2026-05-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_single_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='medium',
            field=models.CharField(choices=[('oil', 'Oil'), ('acrylic', 'Acrylic'), ('watercolor', 'Watercolor'), ('mixed', 'Mixed Media'), ('pencil', 'Pencil / Graphite'), ('digital', 'Digital Print'), ('other', 'Other')], default='oil', max_length=20),
        ),
    ]
